# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
### Multi-stage Dockerfile for MCP Server Memo

# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the entire project
COPY . .

# Build the TypeScript source
RUN npm run build

# Stage 2: Run
FROM node:lts-alpine
WORKDIR /app

# Copy built files and remaining resources from builder
COPY --from=builder /app .

# Expose ports if needed, though MCP server communicates via stdio

# Command to run the server
CMD [ "npm", "start" ]
